### ISSUE TITLE
Set up Apex and calibrate all probes in header tank and BT 3/4 and add probes to BT 1/2

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/CBLS_Wetlab#13]

**Comment by hputnam** [comment]
@daniellembecker please advertise the calibration time for everyone as well

**Comment by daniellembecker** [comment]
Apex is back up and running. I found the issue was that the Apex temperature probe was plugged into the Ethernet port on the Apex brain. I plugged the temperature probe into the correct outlet on the brain and then plugged in the black Ethernet cord into the brain. It flashed orange, yellow, green, blue, and then settled on orange which represents a stable connection. I then saw on the Apex fusion app that the CBLS basement Apex was back online. 
![Uploading IMG_1163.png…]()

**Comment by daniellembecker** [comment]
Apex is back up and running. I found the issue was that the Apex temperature probe was plugged into the Ethernet port on the Apex brain. I plugged the temperature probe into the correct outlet on the brain and then plugged in the black Ethernet cord into the brain. It flashed orange, yellow, green, blue, and then settled on orange which represents a stable connection. I then saw on the Apex fusion app that the CBLS basement Apex was back online.

![IMG_1163](https://github.com/Putnam-Lab/CBLS_Wetlab/assets/40968353/ab52c171-c884-4003-9622-9234b77cf1d5)

![IMG_1164](https://github.com/Putnam-Lab/CBLS_Wetlab/assets/40968353/c7487872-3fc7-460a-a124-d67b8f95c916)

![IMG_1166](https://github.com/Putnam-Lab/CBLS_Wetlab/assets/40968353/bab4e3b7-4a75-4430-90cd-8ea8925d188b)

**Comment by daniellembecker** [comment]
I also calibrated the Apex/Neptune Systems pH (blue), conductivity (black), and temperature (grey) probes on the header tank and blue tanks 3/4 using the 7 and 10 buffers from upstairs for the pH calibration following the Apex fusion app prompts, the 53,000 µS/cm solution from Apex for the conductivity probe following the Apex fusion app prompts, and the lab digital Thermometer to calibrate the temperature probe. This took ~ 20 minutes to calibrate six probes total.

**Comment by hputnam** [comment]
Thank you @daniellembecker !! Can you find the probes and add temp, salinity, and pH to BT 1/2?

**Comment by daniellembecker** [comment]
Yes @hputnam, doing this today!

**Comment by daniellembecker** [comment]
We used a new Apex aquabus cable to connect a third Apex probe module (PM1) unit (labeled Blue Tank 1 and 2) to the second Apex PM1 unit (labeled HT for header tank) underneath Blue Tanks 1 and 2. Attached a pH and temperature probe to the Apex PM1 unit (labeled Blue Tank 1 and 2) and submerged the probes into Blue Tank 1 and 2 which are currently attached by tape until we locate or make another probe holder for the tanks. Calibrated the new pH probe and temperature probes and linked them to the Apex fusion accounts main page. Each of the probes were added to the Apex fusion main page and were labeled as BT1_T for the temperture probe and BT1_PH for the pH probe. We also relabeled the Blue Tank 3 and 4 temperature (BT3_TMP), conductivity (BT3_SAL), and pH (BT3_PH) probes on the Apex fusion main page. 
![tempImageKQb6CJ](https://github.com/Putnam-Lab/CBLS_Wetlab/assets/40968353/c93470b3-4770-4482-b0ab-414f2beb0b63)
![tempImageKL4ZOH](https://github.com/Putnam-Lab/CBLS_Wetlab/assets/40968353/527f6b73-83ac-429b-8522-1ac60829a87a)
![tempImage0Uw6ib](https://github.com/Putnam-Lab/CBLS_Wetlab/assets/40968353/d66ec999-652d-4aff-ac9c-d79f64c59c4b)

**Comment by daniellembecker** [comment]
We noticed that the pH probe from Blue Tanks 3 and 4 was not calibrating properly and after troubleshooting decided we will need to order a new [Neptune Systems pH probe](https://shop.neptunesystems.com/products/ph-probe?variant=14125536378932) or send this one out for service. We also could not find a third [Neptune Systems Conductivity Probe](https://www.bulkreefsupply.com/neptune-systems-lab-grade-conductivity-probe.html) and will need to order this. @hputnam

**Comment by hputnam** [comment]
@daniellembecker the new Apex bundles we got last summer should have included new probes (pH at least). Please look for these in the lab and storage and then only put them on the order request form on Wednesday if you can't find them any where.

**Comment by hputnam** [comment]
@daniellembecker where are you at with this? Did you find any probes to use after looking in all the places? If not please add to order form on 11/9.

**Comment by daniellembecker** [comment]
@hputnam going to do this today as it’s my day to do daily tasks in the wetlab so was just going to do all the things for the day I had signed up for

**Comment by daniellembecker** [comment]
@laurenzane found a Neptune pH and conductivity probe at GSO! Added a new PM2 unit under BT1/2 since PM1 units don’t have a conductivity port and calibrated a conductivity probe (B1_SAL) and added it to the apex fusion main dashboard. Also calibrated and added the pH probe (B3_pH) to BT3/4 into the Apex brain port and added it to the Apex fusion dashboard. Conductivity probe in BT1/2 seems to not be reading correctly (20.6) after installing so going to check Monday if it has worked but I also used an older 53,000 uS/cm solution to calibrate so we may need to order more of the calibration solution if that is causing the error.

![IMG_1350](https://github.com/Putnam-Lab/CBLS_Wetlab/assets/40968353/bad0816e-477a-40e5-9305-ec0464c8c795)

**Comment by hputnam** [comment]
@daniellembecker new probes are on their way UPS tracking [1Z40WV460392207280](https://www.ups.com/track?trackNums=1Z40WV460392207280) Please install and calibrate upon arrival.

**Comment by daniellembecker** [comment]
Replaced and calibrated BT1/2 and BT 3/4 pH probes with new Bulk Reef Supply pH probes (PN 210794) and added magnetic probe rack to BT tank 1/2. Probes are now reading similar values we have been calculating for the Orion star pH probes using the Tris calibration. This makes me think the issue with the older pH probes may have been incompatibility with the newer AOS Apex software updates since sometimes we would get calibration errors that said “Probe cannot be calibrated, check AOS software update version”. @hputnam let me know if you want me to send them to apex or recycle them.

**Comment by hputnam** [comment]
@daniellembecker can you also replace B1_Sal with the new salinity probe as well?

@daniellembecker you can recycle the old pH probe

**Comment by daniellembecker** [comment]
Probe BT 1/2 and BT 3/4 replaced (these probes were from 2019 and 2015, apex recommends only using probes and trusting them for 2 years). They are calibrated and match the Orion star readings now. I noticed after calibration, that the header tank probe is reading ~0.9 higher than what it should be, this probe is from February 2021 so it could be towards its shelf life as well. However it is stating consistent at this reading, so could be okay for now unless you want to order another conductivity probe @hputnam. Moving forward I recommend calibrating the Orion star conductivity probes with 53,000 uS/cm solutions which I have labeled for quarantine tank and BT3/4 and header.
