### ISSUE TITLE
Build pump inflow cover to prevent snails from entering the protein skimmer

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/CBLS_Wetlab#17]
Use black egg crate with the smaller holes than the white egg crate to hot glue a box together that will cover the inflow of the protein skimmer pump in the blue tank to block the snails. 

Soak in freshwater for 24hours after hotgluing.

Attach to protein skimmer pump by 11/10.

**Comment by daniellembecker** [comment]
Completed, could not find black egg crate but found same hole size in an opaque color. Used zip ties instead of hot glue for easy access/changes to box if needed. Will monitor that it is keeping snails out for the next week and make changes if needed.

![image](https://github.com/Putnam-Lab/CBLS_Wetlab/assets/40968353/8b4bb0be-72fa-49dd-b48d-a7ed39fbcaea)
